prroyectociudad/ordenamiento/urls.py
from django.urls import path
# se importa las vistas de la aplicación
from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('parroquia/<int:id>', views.obtener_parroquia, 
            name='obtener_parroquia'),
        path('crear/parroquia', views.crear_parroquia, 
            name='crear_parroquia'),
        path('editar_parroquia/<int:id>', views.editar_parroquia, 
            name='editar_parroquia'),
        # numeros telefonicos
        path('crear/barrio', views.crear_barrio, 
            name='crear_barrio'),
        path('editar/barrio/<int:id>', views.editar_barrio, 
            name='editar_barrio'),
 ]

prroyectociudad/prroyectociudad/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ordenamiento.urls')),
]

prroyectociudad/ordenamiento/models.py
from django.db import models


# Create your models here.
class Parroquia(models.Model):
    ordering = ["tipo_parroquia"]
    verbose_name_plural = "Los Estudiantes"

    opciones_tipo_parroquia = (
        ('urbana', 'Parroquia Urbana'),
        ('rural', 'Parroquia Rural'),
        )

    nombre = models.CharField("parroquia",max_length=30)
    tipo_parroquia = models.CharField("tipo",max_length=30, \
            choices=opciones_tipo_parroquia) 
    # modulos = models.ManyToManyField('Modulo', through='Matricula')

    def __str__(self):
        return "%s - %s" % (
                self.nombre,  
                self.tipo_parroquia)

class Barrio(models.Model):
    opciones_parques = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        )
    nombre = models.CharField("barrio",max_length=30)
    num_viviendas = models.IntegerField("numero de viviendas")
    parques = models.CharField("numero de parques",max_length=30, \
            choices=opciones_parques)
    num_edificios = models.IntegerField("numero de edificios")
    parroquia = models.ForeignKey(Parroquia, related_name='lasparroquias', 
            on_delete=models.CASCADE)

    def __str__(self):
        return "Módulo: %s - %s -%s -%s - %s" % (
                self.nombre,
                self.num_viviendas,
                self.parques,
                self.num_edificios,
                self.parroquia) 

prroyectociudad/ordenamiento/forms.py
from django.forms import ModelForm
from django import forms

from ordenamiento.models import Parroquia, \
        Barrio

class ParroquiaForm(forms.ModelForm): 
    class Meta:
        model = Parroquia 
        fields = ['nombre', 'tipo_parroquia'] 

class BarrioForm(forms.ModelForm): 
    class Meta:
        model = Barrio 
        fields = ['nombre', 'num_viviendas', 'parques','num_edificios','parroquia'] 

class BarrioParroquiaForm(forms.ModelForm): 
    
    def __init__(self, parroquia, *args, **kwargs):
        super(BarrioParroquiaForm, self).__init__(*args, **kwargs)
        self.initial['parroquia'] = parroquia
        self.fields["parroquia"].widget = forms.widgets.HiddenInput()
        print(parroquia)
    
    class Meta:
        model = Barrio 
        fields = ['nombre', 'num_viviendas', 'parques','num_edificios','parroquia'] 

prroyectociudad/ordenamiento/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render

# importar las clases de models.py
from ordenamiento.models import *

# importar los formularios de forms.py 
from ordenamiento.forms import *

# Create your views here.

def index(request):
    """
        Listar los registros del modelo Estudiante, 
        obtenidos de la base de datos.
    """
    # a través del ORM de django se obtiene
    # los registros de la entidad; el listado obtenido
    # se lo almacena en una variable llamada
    # estudiantes
    parroquias = Parroquia.objects.all()
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'parroquias': parroquias, 'numero_parroquias': len(parroquias)}
    return render(request, 'index.html', informacion_template)

def obtener_parroquia(request, id):
    """
        Listar los registros del modelo Estudiante, 
        obtenidos de la base de datos.
    """
    # a través del ORM de django se obtiene
    # los registros de la entidad; el listado obtenido
    # se lo almacena en una variable llamada
    # estudiantes
    parroquia = Parroquia.objects.get(pk=id)
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'parroquia': parroquia}
    return render(request, 'obtener_parroquia.html', informacion_template)

def crear_parroquia(request):
    """
    """
    if request.method=='POST':
        formulario = ParroquiaForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = ParroquiaForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crearParroquia.html', diccionario) 

def editar_parroquia(request, id):
    """
    """
    parroquia= Parroquia.objects.get(pk=id)
    if request.method=='POST':
        formulario = ParroquiaForm(request.POST, instance=parroquia)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = ParroquiaForm(instance=parroquia)
    diccionario = {'formulario': formulario}

    return render(request, 'editarParroquia.html', diccionario) 

def crear_barrio(request):
    """
    """

    if request.method=='POST':
        formulario = BarrioForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = BarrioForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crearBarrio.html', diccionario)

def editar_barrio(request, id):
    """
    """
    barrio = Barrio.objects.get(pk=id)
    if request.method=='POST':
        formulario = BarrioForm(request.POST, instance=barrio)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = BarrioForm(instance=barrio)
    diccionario = {'formulario': formulario}

    return render(request, 'editarBarrio.html', diccionario) 

prroyectociudad/ordenamiento/templates/crearBarrio.html
<h2>Crear Barrio</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

prroyectociudad/ordenamiento/templates/crearBarrioParroquia.html
<h2>Crear Barrio para {{parroquias}}</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

prroyectociudad/ordenamiento/templates/crearParroquia.html
<h2>Crear Parroquia</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

prroyectociudad/ordenamiento/templates/editarBarrio.html
<h2>Editar Barrio</h3>

    <form action="" method="post">
      {% csrf_token %}
      {{formulario.as_p}}
      <p><input type='submit' value='Actualizar'/></p>
    </form>
    
    [<a href="{% url 'index' %}">inicio</a>]

prroyectociudad/ordenamiento/templates/editarParroquia.html
<h2>Editar Parroquia</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Actualizar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

prroyectociudad/ordenamiento/templates/index.html
<h3>Número de Parroquias - {{ numero_parroquias }}</h3>

<ul>
 {% for e in parroquias %}

  <li>
    Parroquia: {{e}} [<a href="{% url 'obtener_parroquia' e.id %}">ver 🔍️</a>] - 
    [<a href="{% url 'editar_parroquia' e.id %}">editar 🔨</a>] 
      <ul>
        {% for t in e.lasparroquias.all %}
          <li>
            <span>
              Barrio: {{t.nombre}}   - [<a href="{% url 'editar_barrio' t.id %}">editar 🔨</a>] 
            </span>
          </li>
        {% endfor %} 
      </ul>
  </li>
  <hr />

{% endfor %} 
</ul>

<br />
[<a href="{% url 'crear_parroquia' %}">agregar Parroquias</a>]

<br />
[<a href="{% url 'crear_barrio'%}">Agregar Barrios</a>]

prroyectociudad/ordenamiento/templates/listadoParroquiaDos.html
<h2>Listado de Parroquias</h3>
<h3>Número de Parroquias {{ numero_parroquias }}</h3>

{% for e in parroquias %}
    
  {{e}}<br/>
  <ul>
  {% for numero in e.barrio_set.all%}
      <li>
          Barrio {{numero}}<br/>
      </li>
  {% endfor %}
  </ul>
  <br/>
{% endfor %}

prroyectociudad/ordenamiento/templates/obtener_parroquia.html
<h3>Datos de Parroquia</h3>

<p><b>Nombre:</b>{{parroquia.nombre}}</p>
<p><b>Tipo:</b>{{parroquia.tipo_parroquia}}</p>


<br/>
[<a href="{% url 'index' %}">inicio</a>]